---
# tasks file for PeterMosmans.customize-gnome

- name: Parse Gnome Shell version
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      gnome-shell --version | sed 's/[^0-9.]*\([0-9.]*\).*/\1/'
    executable: /bin/bash
  register: r_gnome_extension_parse_shell_version
  changed_when: no

- set_fact:
    gnome_shell_version: "{{ r_gnome_extension_parse_shell_version.stdout }}"

- ansible.builtin.debug:
    msg: "Sorry - no Gnome Shell detected... exiting"
  failed_when: true
  when: not r_gnome_extension_parse_shell_version.stdout

- name: Install (font) packages
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: yes
    install-recommends: no
    state: present
  loop: "{{ gnome_packages|default([]) }}"

- name: Ensure that target directory exists
  ansible.builtin.file:
    path: "/home/{{ gnome_user }}/.config/{{ gtk_version }}"
    state: directory
  become_user: "{{ gnome_user }}"
  when: gtk_version is defined

- name: Copy files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ gnome_user }}"
    group: "{{ gnome_user }}"
    mode: 0644
  loop: "{{ gnome_files|default([]) }}"
  loop_control:
    label: "{{ item.src }}"
  tags:
    - files

- name: Download zipped font files
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "/tmp/{{ item.name }}.zip"
  loop: "{{ gnome_fonts|default([]) }}"
  loop_control:
    label: "{{ item.name }}"
  tags:
    - fonts

- name: Unzip font files
  ansible.builtin.unarchive:
    src: "/tmp/{{ item.name }}.zip"
    dest: "/tmp/"
    remote_src: yes
  with_items: "{{ gnome_fonts|default([]) }}"
  tags:
    - fonts

- name: Install fonts
  ansible.builtin.command:
    cmd: mv /tmp/{{ item.fonts }} /usr/local/share/fonts/
  loop: "{{ gnome_fonts|default([]) }}"
  tags:
    - fonts

- name: Refresh font list
  ansible.builtin.command: fc-cache -fv
  tags:
    - fonts

- name: Load Gnome extension information
  include_tasks: get_extension_info.yml
  with_items: "{{ gnome_extensions }}"

- name: Use gnome_extensions_full
  set_fact:
    gnome_extensions: "{{ gnome_extensions_full }}"

- name: Download GNOME Shell extensions
  get_url:
    url: "{{ item.url }}"
    dest: "/tmp/{{ item.name }}.zip"
  loop: "{{ gnome_extensions|default([]) }}"
  loop_control:
    label: "{{ item.name }}"
  tags:
    - extensions

- name: Create GNOME extension directories
  file:
    path: /home/{{ gnome_user }}/.local/share/gnome-shell/extensions/{{ item.name }}
    state: directory
  become_user: "{{ gnome_user }}"
  loop: "{{ gnome_extensions|default([]) }}"
  loop_control:
    label: "{{ item.name }}"
  tags:
    - extensions

- name: Unzip GNOME extensions
  ansible.builtin.unarchive:
    src: "/tmp/{{ item.name }}.zip"
    dest: "/home/{{ gnome_user }}/.local/share/gnome-shell/extensions/{{ item.name }}"
    creates: "/home/{{ gnome_user }}/.local/share/gnome-shell/extensions/{{ item.name }}/metadata.json"
    remote_src: yes
  become_user: "{{ gnome_user }}"
  loop: "{{ gnome_extensions|default([])}}"
  loop_control:
    label: "{{ item.name }}"
  tags:
    - extensions

- name: Enable extensions
  ansible.builtin.command: gnome-shell-extension-tool -e {{ item.name }}
  become_user: "{{ gnome_user }}"
  when: item.enable | default(false)
  loop: "{{ gnome_extensions | default([]) }}"
  loop_control:
    label: "{{ item.name }}"
  register: r_gnome_enable_extension
  changed_when: "'is now enabled' in r_gnome_enable_extension.stderr"
  failed_when: r_gnome_enable_extension.rc != 0 and 'already enabled' not in r_gnome_enable_extension.stderr
  tags:
    - settings

- name: Modify application settings using gsettings
  ansible.builtin.command: gsettings {{ ('--schemadir ' + item.schemadir) if 'schemadir' in item else '' }} set {{ item.schema }} {{ item.key }} {{ item.value }}
  become_user: "{{ gnome_user }}"
  with_items: "{{ gnome_gsettings|default([]) }}"
  tags:
    - settings

- name: Modify application settings using dconf
  ansible.builtin.command: dbus-launch dconf write {{ item.key }} {{ item.value }}
  become_user: "{{ gnome_user }}"
  with_items: "{{ gnome_dconf|default([]) }}"
  tags:
    - settings
    - dconf
